#!/bin/bash

options=(
  style=rounded
  width=3.0
  hidpi=on
  # active_color=0xa04f4f59
  active_color="glow(0x504f4f59)"
  inactive_color=0
)

# note: can try `order=above` with kitty square / no borders?

borders "${options[@]}"
