return {
  flags = { debounce_text_changes = 150 },
  cmd = { 'intelephense', '--stdio' },
  filetypes = { 'php' },
  root_dir = vim.fs.dirname(
    vim.fs.find({ '.git', 'composer.json' }, { upward = true })[1]
  ),
  root_markers = { '.git', 'composer.json' },
  init_options = {
    licenceKey = os.getenv('HOME') .. '/.config/intelephense.txt'
  },
  settings = {
    intelephense = {
      format = {
        enable = true,
      },
      files = {
        exclude = {
          "**/.git/**",
          "**/.svn/**",
          "**/.hg/**",
          "**/CVS/**",
          "**/.DS_Store/**",
          "**/node_modules/**",
          "**/bower_components/**",
          "**/_ci_phpunit_test/**",
          "**/vendor/**/{Tests,tests}/**",
          "**/tmp/**"
        }
      },
      completion = {
        insertUseDeclaration = true,
        fullyQualifyGlobalConstantsAndFunctions = true,
        triggerParameterHints = true,
        maxItems = 100
      },
      phpdoc = {
        returnVoid = false
      },
      stubs = {
        "apache",
        "bcmath",
        "bz2",
        "calendar",
        "com_dotnet",
        "Core",
        "ctype",
        "curl",
        "date",
        "dba",
        "dom",
        "enchant",
        "exif",
        "FFI",
        "fileinfo",
        "filter",
        "fpm",
        "ftp",
        "gd",
        "gettext",
        "gmp",
        "hash",
        "iconv",
        "imap",
        "intl",
        "json",
        "ldap",
        "libxml",
        "mbstring",
        "meta",
        "mysqli",
        "oci8",
        "odbc",
        "openssl",
        "pcntl",
        "pcre",
        "PDO",
        "pdo_ibm",
        "pdo_mysql",
        "pdo_pgsql",
        "pdo_sqlite",
        "pgsql",
        "Phar",
        "posix",
        "pspell",
        "readline",
        "Reflection",
        "session",
        "shmop",
        "SimpleXML",
        "snmp",
        "soap",
        "sockets",
        "sodium",
        "SPL",
        "sqlite3",
        "standard",
        "superglobals",
        "sysvmsg",
        "sysvsem",
        "sysvshm",
        "tidy",
        "tokenizer",
        "xml",
        "xmlreader",
        "xmlrpc",
        "xmlwriter",
        "xsl",
        "Zend OPcache",
        "zip",
        "zlib",
        "redis"
      }
    }
  }
}
