### Simple get
GET https://jsonplaceholder.typicode.com/todos/1

### Simple post with JSON
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json; charset=UTF-8

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}
