local g = vim.g
g.expand_region_text_objects = {}
g.expand_region_text_objects['iw'] = 0
g.expand_region_text_objects['iW'] = 0
g.expand_region_text_objects['i"'] = 0
g.expand_region_text_objects["i'"] = 0
g.expand_region_text_objects['i]'] = 1
g.expand_region_text_objects['il'] = 1
g.expand_region_text_objects['ib'] = 1
g.expand_region_text_objects['iB'] = 1
g.expand_region_text_objects['ic'] = 0
g.expand_region_text_objects['ip'] = 1
g.expand_region_text_objects['ie'] = 0
