# simplify the status
[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# see https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme-dark.toml
# disable icons
[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = [
  { if = "dir", text = "" },
  { if = "exec", text = "" },
  { if = "!dir", text = "" },
]
