# separate prompts with a line between
add_newline = true

# allow commands to run for 2s before timeout
command_timeout = 2000

# left prompt
format = """
${custom.prompt_start}\
$jobs\
$username\
$character\
${custom.prompt_end}\
"""

# right prompt
right_format = """
$cmd_duration
$python
$git_branch
${custom.git_status}
$directory
"""

# what to show when hitting enter on something like a quote
continuation_prompt = '  > '

[jobs]
number_threshold = 1 # always show
style = 'fg:#707082'
format = '[\[$number\]]($style) '

[character]
success_symbol = "[==>](fg:#5521d9)"
error_symbol = "[==>](red)"
vimcmd_symbol = "[--V](dimmed green)"

[cmd_duration]
style = "italic fg:#707082"
format = "[$duration ]($style)"

[git_branch]
style = "fg:#707082"
symbol = " "
format = "[$symbol$branch ]($style)"
truncation_length = 32

[directory]
truncate_to_repo = false
use_logical_path = false
truncation_symbol = '…/'
read_only = ''
style = 'fg:#99A4BC'
format = "[$path]($style)"

# note that substitutions are substituted into the below themselves
# also the presence of substitutions means that fish_style can't be used for directory module
[directory.substitutions]
'~/Documents/Work/internal/blog/hugo/mwcom' = '~blog'
'~/Documents/Work' = '~w'
'~/Documents' = '~docs'
'~/Downloads' = '~down'
'~w/internal/vim/colors/falcon' = '~falcon'
'~w/personify_care' = '~pc'
'~pc/repos/personify-care-platform' = '~pcp'
'~pc/repos/personify-care-test' = '~pct'
'~pc/repos/personify-care-web' = '~pcw'
'~/.config/nvim' = '~nv'
'~/Library/Mobile Documents/com~apple~CloudDocs' = '~icloud'
'~/vaults/zettelkasten' = '~z'
'~/.config/yabai' = '~y'
'~/.config/sketchybar' = '~sb'
'~w/internal/projects/majyk' = '~m'

# name of python virtual env if applicable
[python]
format = '[(\($virtualenv\))]($style) '
style = "fg:#707082"

[custom.git_status]
command = "~/.config/starship/git_status.sh"
when = "true"
format = "$output"

# Special OSC 133 for prompt start / end indication
# See https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md
# See https://sw.kovidgoyal.net/kitty/shell-integration/ for kitty specific things
[custom.prompt_start]
command = 'echo "\\e]133;A\\e\\"'
when = "true"
unsafe_no_escape = true
format = "$output"

[custom.prompt_end]
command = 'echo "\\e]133;B\\e\\"'
when = "true"
unsafe_no_escape = true
format = "$output"
