# don't separate prompts with a line
add_newline = false

# allow commands to run for 2s before timeout
command_timeout = 2000

# left prompt
format = """
$jobs\
$username\
$character
"""

# right prompt
right_format = """
$cmd_duration
$python
$git_branch
${custom.git_status}
$directory
"""

# what to show when hitting enter on something like a quote
continuation_prompt = '  > '

[jobs]
number_threshold = 1 # always show
style = 'fg:#707082'
format = '[\[$number\]]($style) '

[character]
success_symbol = "[==>](blue)"
error_symbol = "[==>](red)"
vimcmd_symbol = "[  ▼](dimmed green)"

[cmd_duration]
style = "italic fg:#707082"
format = "[$duration ]($style)"

[git_branch]
style = "fg:#707082"
symbol = ""
format = "[$symbol$branch ]($style)"
truncation_length = 32

[directory]
truncate_to_repo = false
use_logical_path = false
truncation_symbol = '…/'
read_only = ''
style = 'fg:#99A4BC'
format = "[$path]($style)"

# note that substitutions are substituted into the below themselves
# also the presence of substitutions means that fish_style can't be used for directory module
[directory.substitutions]
'~/Documents/Work/internal/blog/hugo/mwcom' = '~blog'
'~/Documents/Work' = '~w'
'~/Documents' = '~docs'
'~/Downloads' = '~down'
'~w/internal/vim/colors/falcon' = '~falcon'
'~w/personify_care' = '~pc'
'~pc/repos/personify-care-platform' = '~pcp'
'~pc/repos/personify-care-test' = '~pct'
'~pc/repos/personify-care-web' = '~pcw'
'~/.config/nvim' = '~nv'
'~/iCloud' = '~icloud'
'~/.config/yabai' = '~y'
'~/.config/sketchybar' = '~sb'

# name of python virtual env if applicable
[python]
format = '[(\($virtualenv\))]($style) '
style = "fg:#707082"

[custom.git_status]
command = "~/.config/starship/git_status.sh"
when = "true"
format = "$output"
